import * as fs from "fs";
import * as path from "path";
import type { FunctionManifest } from "../analyze/extract";

export function generateApi(manifest: FunctionManifest, outputPath: string): void {
  const lines: string[] = [
    `// Auto-generated by vex CLI — DO NOT EDIT`,
    `import type { FunctionReference } from "@vex/server";`,
    "",
  ];

  // Group functions by module (file), separating public vs internal
  const publicGrouped: Record<string, Record<string, { type: "query" | "mutation" | "action"; argsType: string }>> = {};
  const internalGrouped: Record<string, Record<string, { type: "query" | "mutation" | "action"; argsType: string }>> = {};

  for (const [fnName, fn] of Object.entries(manifest)) {
    const [moduleName, funcName] = fnName.includes(":")
      ? [fnName.split(":")[0], fnName.split(":").slice(1).join(":")]
      : ["default", fnName];

    const target = fn.isInternal ? internalGrouped : publicGrouped;
    if (!target[moduleName]) target[moduleName] = {};

    target[moduleName][funcName] = {
      type: fn.type,
      argsType: fn.args.type === "object" && fn.args.value
        ? `{ ${Object.entries(fn.args.value as Record<string, any>).map(([k, v]) => `${k}: ${validatorTypeToTs(v)}`).join("; ")} }`
        : "Record<string, never>",
    };
  }

  // Generate api object (public functions only)
  lines.push(`export const api = {`);
  for (const [moduleName, funcs] of Object.entries(publicGrouped)) {
    lines.push(`  ${moduleName}: {`);
    for (const [funcName, fn] of Object.entries(funcs)) {
      const refType = `"${fn.type}"`;
      lines.push(`    ${funcName}: { _name: "${moduleName}:${funcName}" as const, _type: ${refType} as const } as FunctionReference<${refType}, ${fn.argsType}, any>,`);
    }
    lines.push(`  },`);
  }
  lines.push(`};`);

  // Generate internal object (internal functions only)
  if (Object.keys(internalGrouped).length > 0) {
    lines.push(``);
    lines.push(`export const internal = {`);
    for (const [moduleName, funcs] of Object.entries(internalGrouped)) {
      lines.push(`  ${moduleName}: {`);
      for (const [funcName, fn] of Object.entries(funcs)) {
        const refType = `"${fn.type}"`;
        lines.push(`    ${funcName}: { _name: "${moduleName}:${funcName}" as const, _type: ${refType} as const } as FunctionReference<${refType}, ${fn.argsType}, any>,`);
      }
      lines.push(`  },`);
    }
    lines.push(`};`);
  } else {
    lines.push(``);
    lines.push(`export const internal = {};`);
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, lines.join("\n") + "\n");
}

function validatorTypeToTs(json: any): string {
  if (!json) return "unknown";
  switch (json.type) {
    case "string": return "string";
    case "number": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    case "any": return "any";
    case "id": return "string";
    case "literal": return typeof json.value === "string" ? `"${json.value}"` : `${json.value}`;
    case "object": return "{ " + Object.entries(json.value || {}).map(([k, v]) => `${k}: ${validatorTypeToTs(v)}`).join("; ") + " }";
    case "array": return `${validatorTypeToTs(json.value)}[]`;
    case "union": return (json.value || []).map((v: any) => validatorTypeToTs(v)).join(" | ");
    case "optional": return `${validatorTypeToTs(json.value)} | undefined`;
    default: return "unknown";
  }
}
