/**
 * Reads the built SPA from dist/index.html and embeds it as a TypeScript
 * string constant in the server package.
 */
import { readFileSync, writeFileSync } from "fs"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const htmlPath = resolve(__dirname, "../dist/index.html")
const outPath = resolve(__dirname, "../../server/src/runtime/dashboard-html.ts")

const html = readFileSync(htmlPath, "utf-8")

// Escape backticks and ${} in the HTML for template literal embedding
const escaped = html
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${")

const output = `// Auto-generated by dashboard build — DO NOT EDIT MANUALLY
// Run \`bun run build\` in packages/dashboard to regenerate
export const dashboardHtml: string = \`${escaped}\`
`

writeFileSync(outPath, output, "utf-8")
console.log(`[dashboard] Embedded ${html.length} bytes → ${outPath}`)
