// Auto-generated by vex CLI — DO NOT EDIT
import * as messages from "../../../examples/chat-app/vex/messages";
import httpRouterModule from "../../../examples/chat-app/vex/http";
import cronsModule from "../../../examples/chat-app/vex/crons";

type FunctionDef = {
  type: "query" | "mutation" | "action";
  isInternal: boolean;
  handler: (ctx: any, args: any) => Promise<any>;
  argsValidator?: Record<string, { json: any }>;
  returnsValidator?: { json: any };
};
export const functions: Record<string, FunctionDef> = {};

for (const [name, fn] of Object.entries(messages)) {
  if (fn && typeof fn === "object" && "_type" in fn && "handler" in fn) {
    const argsValidator = "_argsValidator" in fn ? (fn as any)._argsValidator : undefined;
    const returnsValidator = "_returnsValidator" in fn ? (fn as any)._returnsValidator : undefined;
    const isInternal = "_isInternal" in fn ? !!(fn as any)._isInternal : false;
    functions["messages:" + name] = { type: (fn as any)._type, isInternal, handler: (fn as any).handler, argsValidator, returnsValidator };
  }
}

export const schema = {"tables":{"messages":{"fields":{"body":{"type":"string"},"author":{"type":"string"},"channel":{"type":"string"}},"indexes":[{"name":"by_channel","fields":["channel"]}]}}};

export const httpRouter = httpRouterModule;

export const cronJobsDef = cronsModule;
