// Auto-generated by vex CLI — DO NOT EDIT
import * as comments from "../../../examples/task-manager/vex/comments";
import * as projects from "../../../examples/task-manager/vex/projects";
import * as tasks from "../../../examples/task-manager/vex/tasks";
import * as utils_stats from "../../../examples/task-manager/vex/utils/stats";
import httpRouterModule from "../../../examples/task-manager/vex/http";
import cronsModule from "../../../examples/task-manager/vex/crons";

type FunctionDef = {
  type: "query" | "mutation" | "action";
  isInternal: boolean;
  handler: (ctx: any, args: any) => Promise<any>;
  argsValidator?: Record<string, { json: any }>;
  returnsValidator?: { json: any };
};
export const functions: Record<string, FunctionDef> = {};

for (const [name, fn] of Object.entries(comments)) {
  if (fn && typeof fn === "object" && "_type" in fn && "handler" in fn) {
    const argsValidator = "_argsValidator" in fn ? (fn as any)._argsValidator : undefined;
    const returnsValidator = "_returnsValidator" in fn ? (fn as any)._returnsValidator : undefined;
    const isInternal = "_isInternal" in fn ? !!(fn as any)._isInternal : false;
    functions["comments:" + name] = { type: (fn as any)._type, isInternal, handler: (fn as any).handler, argsValidator, returnsValidator };
  }
}
for (const [name, fn] of Object.entries(projects)) {
  if (fn && typeof fn === "object" && "_type" in fn && "handler" in fn) {
    const argsValidator = "_argsValidator" in fn ? (fn as any)._argsValidator : undefined;
    const returnsValidator = "_returnsValidator" in fn ? (fn as any)._returnsValidator : undefined;
    const isInternal = "_isInternal" in fn ? !!(fn as any)._isInternal : false;
    functions["projects:" + name] = { type: (fn as any)._type, isInternal, handler: (fn as any).handler, argsValidator, returnsValidator };
  }
}
for (const [name, fn] of Object.entries(tasks)) {
  if (fn && typeof fn === "object" && "_type" in fn && "handler" in fn) {
    const argsValidator = "_argsValidator" in fn ? (fn as any)._argsValidator : undefined;
    const returnsValidator = "_returnsValidator" in fn ? (fn as any)._returnsValidator : undefined;
    const isInternal = "_isInternal" in fn ? !!(fn as any)._isInternal : false;
    functions["tasks:" + name] = { type: (fn as any)._type, isInternal, handler: (fn as any).handler, argsValidator, returnsValidator };
  }
}
for (const [name, fn] of Object.entries(utils_stats)) {
  if (fn && typeof fn === "object" && "_type" in fn && "handler" in fn) {
    const argsValidator = "_argsValidator" in fn ? (fn as any)._argsValidator : undefined;
    const returnsValidator = "_returnsValidator" in fn ? (fn as any)._returnsValidator : undefined;
    const isInternal = "_isInternal" in fn ? !!(fn as any)._isInternal : false;
    functions["utils/stats:" + name] = { type: (fn as any)._type, isInternal, handler: (fn as any).handler, argsValidator, returnsValidator };
  }
}

export const schema = {"tables":{"projects":{"fields":{"name":{"type":"string"},"description":{"type":"string"},"color":{"type":"string"}},"indexes":[]},"tasks":{"fields":{"title":{"type":"string"},"description":{"type":"optional","value":{"type":"string"}},"status":{"type":"string"},"priority":{"type":"string"},"projectId":{"type":"string"},"assignee":{"type":"optional","value":{"type":"string"}},"dueDate":{"type":"optional","value":{"type":"number"}},"labels":{"type":"optional","value":{"type":"array","value":{"type":"string"}}}},"indexes":[{"name":"by_project_status","fields":["projectId","status"]},{"name":"by_status","fields":["status"]},{"name":"by_project","fields":["projectId"]}]},"comments":{"fields":{"body":{"type":"string"},"author":{"type":"string"},"taskId":{"type":"string"}},"indexes":[{"name":"by_task","fields":["taskId"]}]}}};

export const httpRouter = httpRouterModule;

export const cronJobsDef = cronsModule;
